CREATE database demo_db;

create table person (
    id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    age int CHECK(age<100)
);

create table item(
id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
person_id int references Person(id) on delete set null,
item_name varchar(200) NOT NULL
);

CREATE table passport (
    id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    passport_number int NOT NULL,
     person_id int UNIQUE REFERENCES person(id) ON DELETE CASCADE
);

create table actor(
    id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    age int CHECK(age>0)
);

create table movie(
    id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    name varchar(200) not null,
    year_of_production int CHECK(year_of_production>1900)
);

create table movie_actor(
actor_id int REFERENCES actor(id),
movie_id int REFERENCES movie(id),
PRIMARY KEY (actor_id, movie_id)
);


insert into person (name, age) values ('Viktor', 34);
insert into person (name, age) values ('Igor', 24);
insert into person (name, age) values ('Sergei', 56);
insert into person (name, age) values ('Taras', 21);


insert into item (person_id, item_name) values (1, 'MacBook Pro');
insert into item (person_id, item_name) values (1, 'iPhone Pro MAX');
insert into item (person_id, item_name) values (1, 'PS5');
insert into item (person_id, item_name) values (3, 'MacBook Air');
insert into item (person_id, item_name) values (3, 'iPhone 5S');
insert into item (person_id, item_name) values (2, 'TV');



